name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-maven-central:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish
        env:
          TAG_NAME: ${{ github.ref_name }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
        run: |
          PUBLISH_VERSION=${TAG_NAME#v}
          ./gradlew sonatypeCentralUpload -PpublishVersion="$PUBLISH_VERSION"
